[package]
name = "asm816_core"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6"
chumsky = { version = "0.12", default-features = false, features = ["std"] }
indexmap = "2.7"
logos = "0.16"
pretty = "0.12"
rustc-hash = "2.1"
smallvec = "1.13"

[dev-dependencies]
tempfile = "3.16"
